export const INTERESTS = [
  { value: "Animal Welfare", label: "Animal Welfare" },
  { value: "Arts", label: "Arts" },
  { value: "Children", label: "Children" },
  { value: "Community", label: "Community" },
  { value: "Conservation and Nature", label: "Conservation and Nature" },
  { value: "Digital", label: "Digital" },
  { value: "Drug Awareness", label: "Drug Awareness" },
  { value: "Education", label: "Education" },
  { value: "Eldercare", label: "Eldercare" },
  { value: "Environment and Water", label: "Environment and Water" },
  { value: "Families", label: "Families" },
  { value: "Health", label: "Health" },
  { value: "Heritage", label: "Heritage" },
  { value: "Humanitarian", label: "Humanitarian" },
  { value: "Mental Health", label: "Mental Health" },
  { value: "Migrant Workers", label: "Migrant Workers" },
  {
    value: "Rehabilitation & Reintegration",
    label: "Rehabilitation & Reintegration",
  },
  { value: "Safety & Security", label: "Safety & Security" },
  { value: "Social Services", label: "Social Services" },
  { value: "Special Needs/Disabilties", label: "Special Needs/Disabilties" },
  { value: "Sports", label: "Sports" },
  { value: "Women & Girls", label: "Women & Girls" },
  { value: "Youth", label: "Youth" },
];
